@startmindmap

+ <img:https://avatars.githubusercontent.com/u/62766039?v=4{scale=0.10}>
++_ <img:https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png{scale=0.20}>
++_ <img:https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png{scale=0.20}>
++_ <img:https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/html/html.png{scale=0.20}>
++_ <img:https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/css/css.png{scale=0.20}>
++_ <img:https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png{scale=0.20}>
@endmindmap